import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { FiCheckCircle } from 'react-icons/fi';
import TableEvaluasiRisiko from '@/components/shared/table/TableEvaluasiRisiko';

const AkarPenyebabTabel = ({ generatedRootCauses, onSelect, selectedId }) => {
    const [selected, setSelected] = useState(selectedId);

    useEffect(() => {
        setSelected(selectedId);
    }, [selectedId]);

    const handleSelect = (row) => {
        setSelected(row.id);
        onSelect(row);
    };

    const data = (generatedRootCauses || []).map(item => ({
        id: item.id,
        jenis: item.jenis,
        deskripsi: item.deskripsi,
        pengendalian: item.pengendalian,
        jenis_pengendalian: item.jenis_pengendalian,
        generation_id: item.generation_id,
        nama: (
            <>
                <div>{item.jenis}</div>
                <div className="fw-light text-muted">{item.deskripsi}</div>
            </>
        ),
        tag: 'Generated by AI'
    }));

    const columns = [
        {
            accessorKey: 'nama',
            header: () => 'Jenis',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'pengendalian',
            header: () => 'Pengendalian',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'jenis_pengendalian',
            header: () => 'Jenis Pengendalian',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'tag',
            header: () => 'Tag',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'tindakan',
            header: 'Tindakan',
            cell: (info) => {
                const isSelected = selected === info.row.original.id;
                return (
                    <button
                        className={`btn btn-sm ${isSelected ? 'btn-primary' : 'btn-light-primary'}`}
                        onClick={() => handleSelect(info.row.original)}
                    >
                        {isSelected ? (
                            <>
                                <FiCheckCircle className="me-1" /> Dipilih
                            </>
                        ) : (
                            'Pilih'
                        )}
                    </button>
                );
            },
        },
    ];

    return (
        <TableEvaluasiRisiko
            title="Hasil Generate Akar Penyebab"
            data={data}
            columns={columns}
        />
    );
};

AkarPenyebabTabel.propTypes = {
    generatedRootCauses: PropTypes.array.isRequired,
    onSelect: PropTypes.func.isRequired,
    selectedId: PropTypes.string,
};

export default AkarPenyebabTabel;
