import { useEffect, useState } from 'react';
import { useNavigate, useParams, useLocation } from "react-router-dom";
import PropTypes from 'prop-types';
import axios from 'axios';
import { FiSave, FiArrowLeft } from 'react-icons/fi';
import CardHeader from '@/components/shared/CardHeader';
import useCardTitleActions from '@/hooks/useCardTitleActions';
import ContentLoaderWrapper from '@/components/shared/ContentLoaderWrapper';
import { showToast } from '@/utils/toast';
import FormEvaluasiRisiko from './FormEvaluasiRisiko';
import AkarPenyebabModal from './AkarPenyebabModal';
import { useInstansi } from '../../context/InstansiContext';
import { useIndukUnitKerja } from '../../context/IndukUnitKerjaContext';
import API_ENDPOINTS from '../../config/apiConfig';

const EvaluasiRisikoTambahContent = ({ title = "Evaluasi Risiko", resetKey }) => {
    const { isRemoved, handleRefresh, handleExpand, handleDelete } = useCardTitleActions();
    const navigate = useNavigate();
    const { identifikasiId } = useParams();
    const { state } = useLocation();  // Get analisisId from state
    const analisisId = state?.analisisId;

    const { idInstansi } = useInstansi();
    const { idIndukUnitKerja } = useIndukUnitKerja();

    const [identifikasiRisiko, setIdentifikasiRisiko] = useState(null);
    const [dataJenisPenyebab, setDataJenisPenyebab] = useState([]);
    const [generatedRootCauses, setGeneratedRootCauses] = useState([]);
    const [loadingGenerate, setLoadingGenerate] = useState(false);
    const [selectedJenisPenyebab, setSelectedJenisPenyebab] = useState(null);
    const [selectedRootCause, setSelectedRootCause] = useState(null);
    const [loading, setLoading] = useState(true);
    const [errorMessage, setErrorMessage] = useState("");
    const [showModal, setShowModal] = useState(false);

    // Form data state
    const [formData, setFormData] = useState({
        identifikasi_risiko_id: identifikasiId,
        analisis_risiko_id: analisisId,
        jenis_penyebab_id: "",
        deskripsi: "",
        jenis: "",
        pengendalian: "",
        jenis_pengendalian: "",
        generation_id: "",
        root_cause_id: "",
        id_instansi: idInstansi,
        id_induk_unit_kerja: idIndukUnitKerja
    });

    useEffect(() => {
        const fetchAllData = async () => {
            setLoading(true);
            try {
                const token = localStorage.getItem('access_token');
                const headers = { Authorization: `Bearer ${token}` };

                const identifikasiRisikoResponse = await axios.get(API_ENDPOINTS.getIdentifikasiRisikoById(identifikasiId),
                    { headers }
                );
                setIdentifikasiRisiko(identifikasiRisikoResponse.data);

                const jenisPenyebabResponse = await axios.get(API_ENDPOINTS.getJenisPenyebabAll(idInstansi),
                    { headers }
                );
                setDataJenisPenyebab(jenisPenyebabResponse.data);
            } catch (error) {
                console.error("Error fetching data:", error);
                setErrorMessage("Gagal mengambil data.");
            } finally {
                setLoading(false);
            }
        };

        fetchAllData();
    }, [idInstansi, identifikasiId]);

    const handleGenerateRootCauses = async () => {
        setLoadingGenerate(true);
        try {
            const token = localStorage.getItem('access_token');
            const response = await axios.post(
                API_ENDPOINTS.postEvaluasiRisikoGenerate,
                { identifikasi_risiko_id: identifikasiId },
                { headers: { Authorization: `Bearer ${token}` } }
            );

            const generationId = response.data.generation_id;

            const rootCauses = response.data.root_causes.map(rootCause => ({
                ...rootCause,
                generation_id: generationId,
                tag: 'Generated by AI'
            }));

            setGeneratedRootCauses(rootCauses);
        } catch (error) {
            console.error("Error generating root causes:", error);
        } finally {
            setLoadingGenerate(false);
        }
    };

    const handleSelectRootCause = (rootCause) => {
        setSelectedRootCause(rootCause);
        setFormData(prev => ({
            ...prev,
            jenis: rootCause.jenis,
            deskripsi: rootCause.deskripsi,
            pengendalian: rootCause.pengendalian,
            jenis_pengendalian: rootCause.jenis_pengendalian,
            generation_id: rootCause.generation_id,
            root_cause_id: rootCause.id
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);

        try {
            const token = localStorage.getItem('access_token');
            const headers = { Authorization: `Bearer ${token}` };

            let payload;
            const generationId = selectedRootCause.generation_id;
            const rootCauseId = selectedRootCause.id;

            if (!generationId || !rootCauseId) {
                showToast("error", "Data AI tidak lengkap: generation_id atau root_cause_id kosong.");
                return;
            }

            payload = {
                ...formData,
                jenis: selectedRootCause.jenis,
                deskripsi: selectedRootCause.deskripsi,
                pengendalian: selectedRootCause.pengendalian,
                jenis_pengendalian: selectedRootCause.jenis_pengendalian,
                generation_id: selectedRootCause.generation_id,
                root_cause_id: selectedRootCause.id
            };

            await axios.post(API_ENDPOINTS.postEvaluasiRisiko, payload, { headers });

            showToast('success', 'Evaluasi Risiko berhasil disimpan!');
            resetKey(prev => prev + 1);
        } catch (error) {
            const msg = error.response?.data?.message || 'Terjadi kesalahan saat menyimpan.';
            showToast('error', msg);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="card stretch stretch-full">
            <CardHeader title={title} refresh={handleRefresh} remove={handleDelete} expanded={handleExpand} />
            <div className="card-body">
                <ContentLoaderWrapper loading={loading} error={errorMessage}>
                    <form onSubmit={handleSubmit}>
                        <FormEvaluasiRisiko
                            identifikasiRisiko={identifikasiRisiko}
                            dataJenisPenyebab={dataJenisPenyebab}
                            selectedValues={{ jenisPenyebab: selectedJenisPenyebab }}
                            handleSelectChange={(name, option) => setSelectedJenisPenyebab(option)}
                            formData={formData}
                            handleInputText={(e) => setFormData({ ...formData, [e.target.name]: e.target.value })}
                            handleGenerateRootCauses={handleGenerateRootCauses}
                            openModal={() => setShowModal(true)}
                        />
                        <div className="d-flex justify-content-end gap-2 mt-3">
                            <button
                                type="button"
                                className="btn bg-soft-danger text-danger"
                                onClick={() => navigate(`/pengelolaan-risiko/identifikasi-risiko/edit/${identifikasiId}`)}
                            >
                                <FiArrowLeft size={16} className="me-2" /> Kembali
                            </button>
                            <button type="submit" className="btn btn-primary">
                                <FiSave size={16} className="me-2" /> Simpan Evaluasi Risiko
                            </button>
                        </div>
                    </form>
                </ContentLoaderWrapper>
            </div>
            <AkarPenyebabModal
                show={showModal}
                onClose={() => setShowModal(false)}
                generatedRootCauses={generatedRootCauses}
                loadingGenerate={loadingGenerate}
                onSelectAI={handleSelectRootCause}
                selectedRootCauseId={selectedRootCause?.id}
            />
        </div>
    );
};

EvaluasiRisikoTambahContent.propTypes = {
    title: PropTypes.string,
    resetKey: PropTypes.func.isRequired,
};

export default EvaluasiRisikoTambahContent;
