import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { FiCheckCircle } from 'react-icons/fi';
import TableEvaluasiRisiko from '@/components/shared/table/TableEvaluasiRisiko';

const EvaluasiRisikoTabel = ({ generatedRootCauses, setSelectedRootCause }) => {
    const [currentSelectedId, setCurrentSelectedId] = useState(null);

    const handleSelect = (row) => {
        setCurrentSelectedId(row.id);
        setSelectedRootCause(row);  // Pass selected row data to parent
    };

    useEffect(() => {
        // If selectedRootCause ID is updated externally, keep the local state in sync
        if (currentSelectedId) {
            setCurrentSelectedId(currentSelectedId);
        }
    }, [currentSelectedId]);

    const data = (generatedRootCauses || []).map(item => ({
        id: item.id,
        jenis: item.jenis,
        deskripsi: item.deskripsi,
        pengendalian: item.pengendalian,
        jenis_pengendalian: item.jenis_pengendalian,
        nama: (
            <>
                <div>{item.jenis}</div>
                <div className="fw-light text-muted">{item.deskripsi}</div>
            </>
        ),
        tag: 'Generated by AI'
    }));

    const columns = [
        {
            accessorKey: 'nama',
            header: () => 'Jenis',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'deskripsi',
            header: () => 'Deskripsi',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'pengendalian',
            header: () => 'Pengendalian',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'jenis_pengendalian',
            header: () => 'Jenis Pengendalian',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'tag',
            header: 'Tag',
            cell: (info) => <span>{info.getValue()}</span>,
        },
        {
            accessorKey: 'tindakan',
            header: 'Tindakans',
            cell: (info) => (
                <button
                    className={`btn btn-sm ${currentSelectedId === info.row.original.id ? 'btn-primary' : 'btn-light-primary'}`}
                    onClick={() => handleSelect(info.row.original)}
                >
                    {currentSelectedId === info.row.original.id ? (
                        <>
                            <FiCheckCircle className="me-1" /> Dipilih
                        </>
                    ) : (
                        'Pilih Data'
                    )}
                </button>
            ),
        },
    ];

    return (
        <TableEvaluasiRisiko
            title="Evaluasi Risiko Akar Penyebab"
            data={data}
            columns={columns}
        />
    );
};

EvaluasiRisikoTabel.propTypes = {
    generatedRootCauses: PropTypes.array.isRequired,
    setSelectedRootCause: PropTypes.func.isRequired,
};

export default EvaluasiRisikoTabel;
